set_property SRC_FILE_INFO {cfile:D:/Documents/Xilinx/MiniZed_MightyRobot/MiniZed_MightyRobot.srcs/constrs_1/new/io.xdc rfile:../../../MiniZed_MightyRobot.srcs/constrs_1/new/io.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports GPIO_O_0[0]]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports GPIO_O_0[1]]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports GPIO_O_0[2]]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports GPIO_O_0[3]]
